### ISSUE TITLE
Non mi esce nulla nella panoramica

### ISSUE THREAD

**Issue by pannelli** [mariocandida80/cronotermostato#10]
Avevo gia un climate.Ho seguito la procedura ma non mi esce nulla.. E' da poco che ho iniziato con home assistant.
Se qualcuno mi può aiutare per guidarmi alla giusta esecuzione della procedura. Grazie

**Comment by mariocandida80** [comment]
Hai già configurato i package? Nella guida, nella sezione prerequisiti, se clicchi su “package” ti spiega come configurarli. Poi hai modificato la parte setup inserendo le tue entità?

**Comment by pannelli** [comment]
ecco gli errori:

2020-10-07 18:41:32 ERROR (MainThread) [homeassistant.components.hassio] Error loading /config/configuration.yaml:   in "/config/configuration.yaml", line 6, column 11: Unable to read file /packages/pkg_cronotermostato_no_climate.yaml.

eccole le prime 5 righe del configuration.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
packages: !include_dir_named packages

default_config:
http:

2020-10-07 19:30:53 WARNING (MainThread) [homeassistant.components.http] The 'base_url' option is deprecated, please remove it from your configuration

Io ho creato la cartella packages. Inserito il file.yaml
Installato hacs e i vari addons

creata la cartella www/immagini/lovelace/ e messi i tre file

Ho gia un climate che funziona con il beok 313

Ecco le impostazioni inserite
 ##--------------------- IMPOSTAZIONI DEL PACKAGE ---------------------##
      setting:
        Tracker: &tracker 'device_tracker.redmi_note_7'           #sostituire con il tracker
        Zona_casa: &zona 'home'                                   #se non si hanno le zone lasciare 'home'
        Servizio Notifica: &servizio 'notify.telegram'            #sostituire con il servizio di notifica
        Climate: &termostato 'climate.ingresso'                           #sostituire con il prorio climate
    ##---------------------                           ---------------------##

Non avevo il file lovelace_yaml.yaml    l'ho creato e ho copiato il contenuto del file all'interno della cartella zippata
grazie.

**Comment by mariocandida80** [comment]
Le riga “ packages: !include_dir_named packages” l’hai messa al secondo rigo in configuration.yaml ?
Dovrebbe essere così:
homeassistant:
  packages: !include_dir_named packages
Prima di packages ci vanno 2 spazi

**Comment by pannelli** [comment]
Grazie mille per l'aiuto. Quella nota è scomparsa. Ora ne sono apparse altre due:

Invalid config
The following integrations and platforms could not be set up:

zeroconf
default_config
Please check your config.

Ecco il mio configuration.yaml

homeassistant:
# Configure a default setup of Home Assistant (frontend, api, etc)
  packages: !include_dir_named packages
  
default_config:

http:
  base_url: https:\\________________.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
    
# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://192.168._._:8123
    service_name: google_say
    
zeroconf:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include climate.yaml

hacs: 
  token: cc5db1____________________________630aedb

duckdns:
  domain: ____________
  access_token: a32ef48e-_____________-be5a-6b05ba_______



Giacchè ci sono volevo chiedere come cambiare impostazioni di configurazione da rete wifi a rete LAN.
L'installazione l'avevo fatta con la rete wifi.
Ora avendo anche un cavo LAN volevo che funzionasse da lì.

**Comment by pannelli** [comment]
Le notifiche si sono azzerate però tra le card non trovo il cronotermostato. Tra le entità trovo i vari comandi "accensione auto da eco term, accensione auto orario 1 term, eco orario, per citarne alcuni

La seconda richiesta sempre valida:
Giacchè ci sono volevo chiedere come modificare le impostazioni di configurazione da rete wifi a rete LAN.
L'installazione l'avevo fatta con la rete wifi.
Ora avendo anche un cavo LAN volevo che funzionasse da lì.

**Comment by mariocandida80** [comment]
Ti consiglio di leggere le guide su https://hassiohelp.eu/ e cercare sul forum dedicato. C’è anche un gruppo su Telegram. Comunque cancella zeroconf e dovrebbe funzionare. Cerca sul sito che ti ho consigliato e, se non dovessi trovare la soluzione, apri una discussione sul forum li che è più pertinente. Chiudo questa issue

**Comment by mariocandida80** [comment]
Per vedere la card, devi ricopiare la parte lovelace come descritto nella guida

**Comment by Vincenzopica** [comment]
ciao, 
anche io ho un pò di prblemi, ho fatto tutto fino al punto 5 poi non ho capito dove devo copiare la arte lovelace. qualcuno può aiutarimi perfavore?
