### ISSUE TITLE
Problemi con 0.118.1

### ISSUE THREAD

**Issue by ivityc** [mariocandida80/cronotermostato#11]
Ciao, ho aggiornato Home Assistant alla Release 0.118.1 e non mi funziona piu la card e il cronotermostato.
Mi compare il seguente errore:
**Custom element doesn't exist: state-switch.**
default: TERMOSTATO
entity: input_select.visualizzazione2
states:
  DOM:
    elements:
      - entity: input_text.casella_vuota
        hold_action:
          action: none
        prefix: Orario termostato domenica
        style:
          background-color: 'rgba(34, 154, 210, 0.5)'
          border-radius: 6px
          color: white
          font-family: Trebuchet MS
          font-size: 120%
          font-weight: bold
          left: 10%
          opacity: 0.8
          pointer-edomts: auto
          right: 10%
...

Prima dell aggiornamento funzionava correttamente

**Comment by mariocandida80** [comment]
Io ho la tua stessa versione e funziona. Controlla se hai l'ultima versione di state-switch. Cancella la cache e ricarica il browser. Così dovrebbe andare.

**Comment by mariocandida80** [comment]
Fammi sapere se facendo così funziona

**Comment by ivityc** [comment]
Penso che il problema sia proprio si la mancanza dello state-switch, anche su HACS non lo trovo come componente , ne installato , ne tra quelli da installare

**Comment by mariocandida80** [comment]
Beh prova ad installarlo a mano ma dovrebbe esserci. Hai cercato in frontend? A me esce

**Comment by ivityc** [comment]
ho aggiunto manualmente lovelace-state-switch-master e creato il link al file state-switch.js e ora rifunziona.
Grazie per il supporto. Ora sto cercando di far funzionare i comandi via telegram... ma per questo apro un'altra issue dopo che mi sarò arreso di capire cosa non va :)

**Comment by mariocandida80** [comment]
Beh c'è qualche problema con l'integrazione. Purtroppo non è mia, prova ad installarla manualmente seguendo la guida ufficiale

**Comment by mariocandida80** [comment]
Ok, allora questa la chiudo. Se hai problemi con telegram, apri tranquillamente un'altra issue e cerchiamo di capire cosa non funziona.
