### ISSUE TITLE
Non riesco a scollegare l'automatico dal device tracker

### ISSUE THREAD

**Issue by pasalino** [mariocandida80/cronotermostato#12]
Vorrei che l'automatismo del mio termostato funzionasse nonostante il device tracker.
Se non imposto un device tracker non parte il riscaldamento in automatico

**Comment by mariocandida80** [comment]
Ciao. Nella guida è spiegato come fare, invece di impostare su auto, imposta su PRE (preriscaldamento) e funzionerà in base agli orari impostati senza tenere conto del tracker.

**Comment by mariocandida80** [comment]
Chiudo l'issue. Se hai problemi riaprine un altro
