### ISSUE TITLE
Fiamma spenta

### ISSUE THREAD

**Issue by marco-81** [mariocandida80/cronotermostato#13]
Ciao Mario,
ho iniziato da poco ad usare homeassistant. Nonostante ciò sono riuscito ad installare il termostato. il problema è che la fiamma rimane sempre grigia. So che è un problema nota e ho letto la spiegazione di come risolverlo ma ahime non ho capito.
Per darti qualche info in più posso dirti che io avevo già un oggetto climate installato (ovvero il condizionatore della samsung). 
Come installazione,per il tuo cronotermostato, ho fatto quella standard perchè il climate esistente deve essere indipendente da quello nuovo. Il tuo cronotermostato mi permetterà di accendere la caldaia a certi orari e temperature mentre mentre il climate del condizionatore appunto deve rimandere indipendente perchè segue la produzione del fotovoltaico.

Fammi sapere.
grazie
Marco

**Comment by mariocandida80** [comment]
Ma tu puoi avere quanti climate vuoi, basta che gli dai un nome diverso ad ognuno. Quindi quale package hai installato? In normale o il no_climate? Per il primo, dovrebbe andare in automatico la fiamma mentre per il secondo va fatta una modifica in Lovelace come da guida.

**Comment by marco-81** [comment]
Ciao Mario,
Io ho installato quello normale, però la fiamma non funziona (si vede sempre grigia).Ho provato anche a cancellare tutto rifare tutto da capo ma la fiamma non funziona. Come sistema operativo ho 4,16 e versione di home assistant 0,118,5.

Ti faccio una domanda da profano però magari permette di risolvere il problema. Nel tuo codice c'è scritto.
 - entity: sensor.riscaldamento_hvac_action
        image: /local/immagini/lovelace/fiamma.gif
        state_filter:
          heat: brigtness(100%)
          idle: brightness(50%) saturate(0.1)
          'off': brightness(50%) saturate(0.1)

Se io guardo nelle entità di home assistant la sensor.riscaldamento_hvac_action non la trovo è normale?
Grazie
Ciao
Marco

**Comment by mariocandida80** [comment]
Ciao. 
Se hai scaricato la versione normale, dovresti trovarti quel sensore. 
In strumenti sviluppatore cerca hvac e vedi come si chiama il sensore. Ma forse hai cambiato il nome del climate nel package?

**Comment by marco-81** [comment]
Riparto da capo. cancello il file dalla directory pagkages, riavvio, cancello le entità che sono rimaste.

prendo il tuo file pkg_cronotermostato.yaml lo apro e modifico questa parte
      setting:
        Interruttore Caldaia: &caldaia 'switch.shellyem_contatto'           #sostituire con l'interruttore che attiva la caldaia
        Sensore Temperatura: &sens_temp 'sensor.shellyht_bagno_nero'      #sostituire con il sensore della temperatura
        Tracker: &tracker 'device_tracker.asus_x00hd'
        Zona_casa: &zona 'home'

carico il file sul raspberry nella directory packages. riavvio
Poi vado in panoramica, aggiungo una nuova scheda e incollo all'interno il contenuto di lovelace_yaml
Quindi nella panoramica appare il termostato. mi indica la temperatura e se l'aumento si attiva il contatto che uso per accedere la caldaia.
Ma la fiamma rimane sempre grigia.

Anche questa volta in strumenti sviluppatore non trovo sensor.riscaldamento_hvac_action

Fammi sapere...
Grazie
Ciao
Marco

**Comment by mariocandida80** [comment]
Probabilmente il problema è il componente "attribute", forse non si è installato correttamente. 
Prova a rimuoverlo, riavvia e poi reinstallarlo. 
Fammi sapere se così funziona.

**Comment by marco-81** [comment]
Ciao,
ho risolto.Nel tuo file del package alla riga 185 c'è scritto cosi
  - platform: attributes 
    friendly_name: "interruttore_caldaia"
    attribute: hvac_action
    entities:
      - climate.riscaldamento

Io ho scritto cosi:
  - platform: template
    sensors:
      riscaldamento_hvac_action:
        friendly_name: "hvac_action"
        value_template: "{{ state_attr('climate.riscaldamento', 'hvac_action') }}"   

Non chiedermi perchè ma ora funziona. :-). Però sarebbe interessante capire perchè ora funziona. Magari centra qualcosa con l versione di home assistant?

Tra l'altro qualche riga + sotto trovo questa scritta
  - platform: history_stats
    name: tempo accensione termostato
    entity_id: switch.sonoff_10004b541f
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

Li al posto di switch.sonoff_10004b541f bisogna mettere il proprio switch giusto?

grazie
ciao
Marco

**Comment by mariocandida80** [comment]
Ciao Marco, 
come hai fatto tu hai aggirato il problema. 
Io ho usato "attribute" per renderlo fruibile a più persone senza modificarlo. Chi usa il pacchetto no_climate poi avrebbe problemi con Lovelace. 
In seguito cercherò altre soluzioni per cercare di far apportare meno modifiche possibili all'utente finale così sarà più semplice ed universale. 
Comunque, come ti dicevo prima, hai un problema con il componente attribute. Prova a disinstallarlo e reinstallarlo. 
Quel componente, tramite la parte sensor che hai modificato, va a creare il sensore che accende e spegne la fiamma. 
Per quanto riguarda la parte del sensore tempo accensione termostato, ho sbagliato io. Appena posso lo correggo. 
Questo sensore lo vorrei aggiungere alla card ma per ora non l'ho ancora fatto. 
Fai la prova che ti dicevo con attribute e fammi sapere.

**Comment by mariocandida80** [comment]
Ho aggiornato la.parte dove c'era lo switch

**Comment by marco-81** [comment]
ehm come faccio a disinstallare e reinstallare il componente attribute?
grazie
ciao
Marco

**Comment by mariocandida80** [comment]
Menu di destra, HACS. 
Clicca su integrations e poi cerca attribute.  
In basso a destra ci sono 3 puntini, cliccaci su e poi clicca su uninstall. 
Poi riavvia e reinstalla attribute
