### ISSUE TITLE
Più termostati

### ISSUE THREAD

**Issue by valer90io** [mariocandida80/cronotermostato#16]
Salve,

Ho inserito il primo termostato, devo inserirne altri 3. Ho provato ad aggiungere il secondo con la procedura descritta.
Visual Studio mi dà più di 160 errori, poi ho notato che è la versione 2.5. Vorrei sapere la logica per inserire altri termostati e quali righe modificare. Mi dice termostato22 undefined.
Come devo fare per aggiungerne altri? Grazie mille.

**Comment by mariocandida80** [comment]
Non puoi aggiungere più di 2 termostati. Se ne hai altri, dovresti modificare il nome tutte le entità e le automazioni.

**Comment by valer90io** [comment]
Sto provando il termostato, in modalità ECO abbassando la temperatura di notte, vorrei sapere perchè al mattino lo trovo in manuale. Sbaglio qualcosa??

**Comment by mariocandida80** [comment]
Lo metti tu in modalità eco o imposti un orario per farlo passare in automatico in modalità eco? Giusto per provare e capire dove sta il problema.

**Comment by valer90io** [comment]
Ho messo su acceso Modalità ECO orario, Modalità di uscita ECO, e poi ho selezionato sotto ECO. Praticamente ho fatto entrambe le cose.
Quindi devo solo mettere uno orario ECO e lasciarlo in modalità manuale?

**Comment by mariocandida80** [comment]
La modalità ECO non accende o spegne il termostato ma cambia solo la temperatura. Se hai il termostato spento non serve mentre se lo hai accesso, qualunque sia la modalità (manuale, auto o preriscaldamento) ti abbassa la temperatura a quella che hai impostato all'ora che hai selezionato e riporta alla temperatura precedente quando arriva l'ora dello spegnimento della modalità.
