### ISSUE TITLE
Tracker 

### ISSUE THREAD

**Issue by lorros-ghub** [mariocandida80/cronotermostato#17]
È possibile integrare più trackers. Grazie.
Buone feste.

**Comment by andreanilorenzo** [comment]
Non ho provato, ma penso che puoi utilizzare un gruppo.
Prova a guardare in questa guida:

https://indomus.it/componenti/componente-home-assistant-device-tracker/

**Comment by mariocandida80** [comment]
Come ti hanno già risposto, puoi creare un gruppo per il tracker e inserisci quello nel package.

**Comment by lorros-ghub** [comment]
Si già fatto, funziona. Grazie mille. 

Inviato da Yahoo Mail su Android 
 
  Il sab, 26 dic, 2020 alle 10:38, Tlod80<notifications@github.com> ha scritto:   


Come ti hanno già risposto, puoi creare un gruppo per il tracker e inserisci quello nel package.
