### ISSUE TITLE
gestione di più tracker o di un gruppo per modlaità home o away

### ISSUE THREAD

**Issue by fireport** [mariocandida80/cronotermostato#18]
Innanzi tutto grazie per lo splendido lavoro !
Vorrei sapere se è possibile aggiungere la gestione di più tracker o di un gruppo per capire se in casa c'è qualcuno oppure no.
Grazie

**Comment by mariocandida80** [comment]
Ti ringrazio. Ovviamente puoi creare un gruppo per il tracker e mettere il gruppo nella parte setting del package. 
Puoi dare uno sguardo qui:
https://www.home-assistant.io/integrations/group/

**Comment by fireport** [comment]
Grazie per il suggerimento
