### ISSUE TITLE
error

### ISSUE THREAD

**Issue by riddik14** [mariocandida80/cronotermostato#2]
ERROR (MainThread) [homeassistant.config] Invalid config for [homeassistant]: invalid slug Pkg_cronotermostato_V1.1 (try pkg_cronotermostato_v1_1) for dictionary value @ data['packages']. Got OrderedDict([('Pkg_cronotermostato_V1.1', OrderedDict([('homeassistant', OrderedDict([('customize', OrderedDict([('package.node_anchors', OrderedDict([('customize', OrderedDict([('package', 'Cronotermostato'), ('version', 1.0), ('author', 'MARIO @tlod80'), ('reference', 'www.hassiohelp.eu')])), ('expose', OrderedDict([('package', 'Cronotermostato'), ('version', 1.0), ('author', 'MARIO @tlod80'), ('reference', 'www.hassiohelp.eu'), ('haaska_hidden', False), ('homebridge_hidden', False)])), ('s.... (See /config/configuration.yaml, line 1). 

perche questo errore?

**Comment by riddik14** [comment]
Configurazione non valida
invalid slug Pkg_cronotermostato_V1_1 (try pkg_cronotermostato_v1_1) for dictionary value @ data['packages']

**Comment by riddik14** [comment]
il problema e il nome del package, l'ho rinominato solo cronotermostato e ora il controllo configurazione ha dato ok

**Comment by mariocandida80** [comment]
Si, c’era il nome sbagliato, aveva un punto. L’ho rinominato già. Grazie
