### ISSUE TITLE
perdita setpoint

### ISSUE THREAD

**Issue by fireport** [mariocandida80/cronotermostato#22]
Ciao, sto utilizzando proficuamente il tuo termostato ma, ogni volta che riavvio home assistant o passo da auto  ad eco perdo l'impostazione del setpoint che torna al valore impostato per eco.
Sbaglio qualcosa ?
Grazie

**Comment by mariocandida80** [comment]
Ciao, c'è qualcosa che non va perché non dovrebbe perdere il valore. 
Cerchiamo di andare per esclusione. 
Per prima cosa controlla la versione del package. Basta cliccare sulla temperatura della card del cronotermostato e ti dice la versione. L' attuale è la 2.6. 
Hai apportato modifiche al package?
Forse hai la memoria piena? Prova a vedere se le varie entità vengono registrate.

**Comment by fireport** [comment]
Ciao, la versione del package è la 2.6 senza modifiche con gli addon per la programmazione settimanle e telegram.
Nella scheda trovo impostata sempre la temperatura di 18 gradi che è quella impostata per l'eco mode. Quando scatta la fascia di accensione il termostato non scatta per chè la temperatura è circa 18 gradi ma non i 21 che voorei. Se imposto di nuovo la temperatura il termostato scatta

**Comment by mariocandida80** [comment]
Ti faccio una serie di domande per capire il problema.
Tu lasci il termostato sempre in modalità auto e ti ritrovi la temperatura più bassa?
Hai impostato modalità in uscita eco?

**Comment by fireport** [comment]
Credo ci sia solo un problema di visualizzazione

![immagine](https://user-images.githubusercontent.com/3115120/105580444-bc3f4600-5d8c-11eb-9d6d-f12a583edc10.png)
Come vedi dall'immagine, il termostato si è acceso ma il setpoint visualizzato rimane quello impostato per eco e io non ho modo di sapere quel'è quello impostato per auto (o non l'ho trovato).
Per rispondere alle tue domande:
Il termostato è in auto e mi trovo sempre il setpoint per eco
Ho impostato modalità di uscita eco

Grazie

**Comment by fireport** [comment]
Questo è lo stato attuale dopo che il termostato è andato in eco perchè non c'era nessuno a casa
![immagine](https://user-images.githubusercontent.com/3115120/105609899-9cb81580-5dac-11eb-8e0a-179b685a9f82.png)
Come vedi il termostato è spento perchè la temperatura è superiore al setpoint per eco. E' come se non capisse che sono rientrato. Rimane il problema di visualizzazione

**Comment by mariocandida80** [comment]
Forse il problema è il tracker? Non risulta che rientri a casa o quando sei a casa magari risulta che esci?
Fai una prova. 
Imposta manualmente la modalità eco e poi metti in modalità auto o manuale e vedi se cambia la temperatura. 
Se la temperatura varia, il problema probabilmente è quello. 
La temperatura per quando il termostato è acceso si imposta solo dalla schermata principale.

**Comment by fireport** [comment]
Ho trovato la causa del problema: era l'addon per la programmazione settimanale.
Rimosso quello, il package funziona come un orologio.
Grazie ancora per l'ottimo lavoro

**Comment by mariocandida80** [comment]
Beh riprova ad installarlo e vedi se funziona bene perché quell'addon non va a modificare la temperatura.
Io personalmente non lo uso il settimanale ma chi lo usa non ha riscontrato problema. 
Riprova, magari va
