### ISSUE TITLE
problema platform: template

### ISSUE THREAD

**Issue by lollox80** [mariocandida80/cronotermostato#24]
Ciao, ho notato un problema:
non so se deriva dalle ultime versioni di Home Assistant o dalla mia installazione

nel pkg_cronotermostato_no_climate se mantengo i platform template non mi legge i sensori

Per esempio:

  - platform: template
    sensors:
      temperatura_attuale:
        friendly_name: "temperatura attuale"
        value_template: "{{ state_attr('*termostato', 'current_temperature') }}"
        unit_of_measurement: °C

  - platform: template
    sensors:
      temperatura_impostata:
        friendly_name: "temperatura impostata"
        value_template: "{{ state_attr('*termostato', 'temperature') }}"
  - platform: attributes
    friendly_name: "interruttore_caldaia"
    attribute: hvac_action
    entities:
      - *termostato
  - platform: template
    sensors:
      versione_attuale_term:
        friendly_name: "Versione attuale termostato"
        value_template: "{{ state_attr('sensor.temperatura_attuale', 'Version') }}"

Se li sostituisco con il mio  climate invece funzionano : 

  - platform: template
    sensors:
      temperatura_attuale:
        friendly_name: "temperatura attuale"
        value_template: "{{ state_attr('climate.aria_condizionata_2', 'current_temperature') }}"
        unit_of_measurement: °C

  - platform: template
    sensors:
      temperatura_impostata:
        friendly_name: "temperatura impostata"
        value_template: "{{ state_attr('climate.aria_condizionata_2', 'temperature') }}"
  - platform: attributes
    friendly_name: "interruttore_caldaia"
    attribute: hvac_action
    entities:
      - *termostato
  - platform: template
    sensors:
      versione_attuale_term:
        friendly_name: "Versione attuale termostato"
        value_template: "{{ state_attr('sensor.temperatura_attuale', 'Version') }}"

**Comment by mariocandida80** [comment]
Ciao. Nella guida, nella sezione dell'installazione no_climate,  c'è scritto:

sostituire *termostato con la proprio entità climate (per esempio climate.riscaldameto) alle righe 161, 168, 173 e 1226.

**Comment by lollox80** [comment]
Grazie, mi era sfuggita quella istruzione

**Comment by mariocandida80** [comment]
Tranquillo, succede
