### ISSUE TITLE
Card non visibile

### ISSUE THREAD

**Issue by gigaflo** [mariocandida80/cronotermostato#29]
Ciao @mariocandida80,
ho seguito tutta la procedura, ma al momento di visualizzare la card nella lovelace non compare nulla.
Mi spiego meglio:
in fase di modifica e configurazione scheda, nell'editor visivo vedo la scheda ed ha anche tutti i comandi attivi;
appena salvo la scheda, la card non è più visibile.

Ho provato a cancellare la cache ma niente.

In attesa di riscontro, ti ringrazio.

P.S. Complimenti per il lavoro.

**Comment by gigaflo** [comment]
Risolto,
grazie

**Comment by fireport** [comment]
Ciao gigaflo, ho anch'io lo stesso problema, come hai risolto ?

**Comment by gigaflo** [comment]
Ciao @fireport,
purtroppo ancora non ho risolto, mi sono accorto adesso che per errore ho chiuso la discussione.
La apro di nuovo e aspettiamo info da @mariocandida80.

**Comment by gigaflo** [comment]
Ciao @fireport,
purtroppo ancora non ho risolto, mi sono accorto adesso che per errore ho chiuso la discussione.
La apro di nuovo e aspettiamo info da @mariocandida80.

**Comment by fabrizio97726** [comment]
ciao qualcuno ha risloto? io ho lo stesso problema: Custom element doesn't exist: state-switch.

**Comment by fabrizio97726** [comment]
RISOLTO!se dovessi avere problemi di visualizzazione della card è percheè non hai installato in HACS button card, card mod, state switch e attributes.

**Comment by mariocandida80** [comment]
Scusate il ritardo nella risposta. Ho visto che avete già risolto. Chiudo. Se avete problemi, riapritelo pure e sarò felice di rispondervi, stavolta velocemente
