### ISSUE TITLE
pkg_cronotermostato_v1_2_no_climate errore

### ISSUE THREAD

**Issue by lollox80** [mariocandida80/cronotermostato#3]
Ho corretto il file perchè c'era un problema di digitazione
[pkg_cronotermostato_v1_2_no_climate.zip](https://github.com/mariocandida80/cronotermostato/files/4107591/pkg_cronotermostato_v1_2_no_climate.zip)

**Comment by mariocandida80** [comment]
Grazie, anche sull’altro file non accettava la V maiuscola. 
Ora dovrebbero funzionare entrambi.
