### ISSUE TITLE
Custom element doesn't exist: state-switch.

### ISSUE THREAD

**Issue by Stasky1968** [mariocandida80/cronotermostato#4]
Sto cercando di installare il cronotermostato ma quando provo a copiare il file lovelace_raw.yaml mi da errore Custom element doesn't exist: state-switch.

Naturalmente il componente è installato e configurato in lovelace configuration

resources:
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/lovelace-card-mod/card-mod.js
  - type: module
    url: /community_plugin/lovelace-state-switch/state-switch.js

**Comment by mariocandida80** [comment]
Hai una versione aggiornata? C'è stato un problema con questo componente all'inizio che è stata rilasciata la versione 0.107 di Home Assistant ma con gli ultimi aggiornamenti è stato risolto il bug. Controlla che la versione di state-switch sia la 6.

**Comment by Stasky1968** [comment]
verificato  , versione di state-switch è la 6.

**Comment by mariocandida80** [comment]
Purtroppo il problema è sorto con la versione 0.107 di home Assistant. Alcune custom card non funzionano bene anche se questa l’hanno sistemata. Procedi a tentativi. 
Verifica di avere la versione più aggiornata di Home Assistant (0.107.7). Se hai una versione vecchia, 0.106 o anche più vecchia e non vuoi aggiornarla, installa una versione più vecchia di state-switch (la 5 o la 4). 
Prova a creare un’altra card state-switch e vedi se funziona. 
All’inizio che è uscito questo bug, io avevo risolto momentaneamente creando una card picture-element nella stessa tab dove era il termostato.

**Comment by mariocandida80** [comment]
> verificato , versione di state-switch è la 6.

sei riuscito a farlo funzionare?

**Comment by Stasky1968** [comment]
niente da fare mi sa che sono io imbranato , ho aperto un issue su state-switch

**Comment by mariocandida80** [comment]
Ma da hacs, state-switch ti risulta verde? Prova ad usare una card con state switch e vedi se funziona

**Comment by Stasky1968** [comment]
da hacs , risulta verde

Se apro una nuova card e scrivo

type: 'custom:state-switch'

il risultato è custom element doesn't  exist: state-switch.



Il giorno lun 6 apr 2020 alle ore 12:57 mariocandida80 <
notifications@github.com> ha scritto:

**Comment by mariocandida80** [comment]
Mi è sorto un dubbio. Dalla versione 0.107 non si aggiungono più manualmente le resources ma solo in automatico se installate da hacs. Prova ad andare in community e poi su setting. Dovrebbe comparirti un messaggio, non ricordo di preciso cosa dice ma grossomodo che ti sposta dei file, se non sbaglio. Clicca su ok, se non lo hai già fatto.

**Comment by Stasky1968** [comment]
Grande , era proprio quello , grazie mille sei stato gentilissimo

Il giorno mar 7 apr 2020 alle ore 12:19 mariocandida80 <
notifications@github.com> ha scritto:

**Comment by ocram76** [comment]
Ciao scusate se mi intrometto, ma anche io ho lo stesso identico problema.
Io ho l'ultima versione di hassio e anche l'ultima di state switch, ricevo sempre lo stesso errore.
Ho fatto l'installazione da HACS e poi ho aggiunto a lovelance tramite il tasto presente nella pagina della del add on. Gentilmente puoi darmi una dritta?
Grazie 1000 per la risposta e il lavoro magnifico svolto.

**Comment by mariocandida80** [comment]
Come suggerito prima, prova ad aprire hacs e poi vai su setting. Dovrebbe esserci un messaggio, di preciso non ricordo cosa c’è scritto ma qualcosa del tipo che sposta dei file. Clicca su ok e dovrebbe andare

**Comment by ocram76** [comment]
Scusami ma se apro hacs e poi setting non mi da nessun messaggio. Sono alle prime armi sorry

**Comment by mariocandida80** [comment]
Tranquillo. Allora fai così. Apri hacs, poi il plugin state-switch. Di che colore è? Se è rosso, probabilmente non lo hai aggiunto a lovelace. Aprendo state switch da hacs, in alto ti uscirà il messaggio “aggiungi a lovelace”, clicca su ok. Dopo fai un controllo. Sempre da hacs scorri a destra e clicca su setting e vedi se ti da qualche messaggio.

**Comment by ocram76** [comment]
Ciao Buongiorno
In hacs le icone sono tutte verdi in quanto avevo aggiunto a lovelance mediante il tasto "aggiungi a lovelance" in setting di hacs nessun messaggio. Sono andato a vedere se erano state aggiunte anche alle resource sotto a configuration lovelance dashboard e c'erano tutte e tre le voci e le ho lasciate cosi senza modificarle. Poi ho inserito all'interno di packages i due pacchetti il settimanale e il cronotermostato variando solo i parametri da te indicati, solita verifica della configurazione e poi restart. Sono andato poi su  configure UI, aggiungi card in manuale e ci ho copiato il contenuto del file raw del settimanale e da qui l'errore. Secondo te ho sbagliato qualcosa? Grazie infinite. Scusami se mi sono dilungato.

**Comment by Stasky1968** [comment]
Ha me il messaggio è apparso dopo che ho aggiornato HACS
Dopo aver cliccato ok sul messaggio , ho dovuto rifare "aggiungi a
lovelace" per tutti plugin installati

Il giorno mer 8 apr 2020 alle ore 06:14 mariocandida80 <
notifications@github.com> ha scritto:

**Comment by mariocandida80** [comment]
> Ciao Buongiorno
> In hacs le icone sono tutte verdi in quanto avevo aggiunto a lovelance mediante il tasto "aggiungi a lovelance" in setting di hacs nessun messaggio. Sono andato a vedere se erano state aggiunte anche alle resource sotto a configuration lovelance dashboard e c'erano tutte e tre le voci e le ho lasciate cosi senza modificarle. Poi ho inserito all'interno di packages i due pacchetti il settimanale e il cronotermostato variando solo i parametri da te indicati, solita verifica della configurazione e poi restart. Sono andato poi su configure UI, aggiungi card in manuale e ci ho copiato il contenuto del file raw del settimanale e da qui l'errore. Secondo te ho sbagliato qualcosa? Grazie infinite. Scusami se mi sono dilungato.

Come dice Stasky1968, forse devi aggiornare HACS perché ora in lovelace le resource non compaiono più. Prova a vedere se devi aggiornarlo e poi controlla in setting. Se ti esce il messaggio, magari ricopialo qui per le altre persone che hanno lo stesso problema.

**Comment by ocram76** [comment]
![20200408_090657](https://user-images.githubusercontent.com/60976948/78755769-febca100-7979-11ea-875d-1f0ba0153b8d.jpg)

![20200408_090722](https://user-images.githubusercontent.com/60976948/78755913-3b889800-797a-11ea-8af4-150e3b4e1dc8.jpg)
A me non ha fatto aggiornamenti HACS di recente, ho la versione 0.23.2

**Comment by mariocandida80** [comment]
Mhm...ma dopo che hai installato la custom card, hai cliccato anche su aggiungi a lovelace?

**Comment by ocram76** [comment]
si si e trovo in lovelance dash board le resource.
se riporto hacs alla versione precedente e poi provo ad aggiornare di nuovo secondo te si potrebbe risolvere qualcosa? oppure faccio downgrade della castom card?

**Comment by mariocandida80** [comment]
Beh se hai home Assistant aggiornato e hacs aggiornato è molto strano che non ti sposti i file. Prova a fare il downgrade di hacs, riavvia, fai l’upgrade, riavvia e poi controlla in setting. Se nemmeno esce, prova ad installare una nuova card e vedi se funziona
