### ISSUE TITLE
pulsante in lovelace 

### ISSUE THREAD

**Issue by riddik14** [mariocandida80/cronotermostato#5]
ciao noto che dagli screenshoot la funzione selezionata(auto man ecc) è evidenziata in giallo, a me no. da cosa dipende? dal tema che uso in hassio per caso?

**Comment by mariocandida80** [comment]
Ciao, non credo che dipenda dal tema ma piuttosto dalla custom card-mod. Hai installato tutti e 4 i plugins?

**Comment by riddik14** [comment]
Me lo faceva già prima. Ho messo tema standard ma niente
![image](https://user-images.githubusercontent.com/37450907/78770807-67624880-798f-11ea-8ff5-a2db73ce4716.jpg)
![6B0C4C77-C201-40ED-9469-F76D7EC4A2BB](https://user-images.githubusercontent.com/37450907/78770867-8365ea00-798f-11ea-8c32-fbc1dafa1e43.jpeg)

Come vedi dalle foto ho attivato con manuale ma il tasto non resta illuminato percui non so che modalità è attiva

**Comment by mariocandida80** [comment]
Di sicuro è card-mod il problema. Fai i seguenti controlli:
Controlla di avere l’ultima versione di home Assistant 
Controlla di avere l’ultima versione di hacs
Controlla di avere l’ultima versione di card mod
Controlla che il plugin card-mod risulti verde
Apri hacs e poi vai in setting e controlla se c’è una notifica che ti fa spostare i file dei custom component. 
Controlla e fammi sapere

**Comment by riddik14** [comment]
Tutto verde e già spostato tutte le resources. La card hi la versione 13 e tutto il resto aggiornato

**Comment by mariocandida80** [comment]
Dalla foto vedo che hai modificato la card. Prova a ricopiarla e controlla. 
Prova a creare una card con l’entity input_select.visualizzazione e controlla che quando clicchi sui pulsanti delle modalità, cambi effettivamente la modalità. Quando clicchi su auto e pre ci metterà poco più di 1 secondo e passerà prima da off. È normale

**Comment by riddik14** [comment]
![1819C18D-1985-4857-9F5C-98E2B4B03254](https://user-images.githubusercontent.com/37450907/78778422-8b2b8b80-799b-11ea-9b5f-364504aabc9d.jpeg)
Dall’app dopo che ho re installato la card ora sembra funzionare

**Comment by mariocandida80** [comment]
Forse era corrotto qualche file della card. Meglio così

**Comment by riddik14** [comment]
allora da ulteriori verifiche sull'app del iphone funziona come hai visto in foto, mentre, su chrome no. quindi è qualcosa di legato al frontend di hassio probabilmente

**Comment by mariocandida80** [comment]
Ho provato ad aprirlo con chrome su mac e a me funziona, sinceramente non so che dirti.

**Comment by riddik14** [comment]
Provo a pulire la cache e vedo che succede

**Comment by mariocandida80** [comment]
Ok, fammi sapere se va. Altrimenti prova anche con un altro browser

**Comment by riddik14** [comment]
il pulsante va sia in chrome che app
