### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by Stasky1968** [mariocandida80/cronotermostato#6]
Ciao scusa ti disturbo di nuovo

sembra che non mi carichi il file pkg_cronotermostato_no_climate.yaml

File inserito in /config/packages

nel file configuration.yaml ho messo
packages: !include_dir_named packages 
preceduto da due spazi

**Comment by mariocandida80** [comment]
Il file configuration.yaml deve iniziare così:

homeassistant:
  packages: !include_dir_named packages

La stringa va inserita subito dopo homeassistant: e non in qualsiasi posto come altri include tipo le automazioni o altro. 
Altra cosa, mi raccomando di chiamare la cartella packages, con la s finale. In tanti, anche io, sbagliano.

**Comment by Stasky1968** [comment]
Grazie
messa subito dopo homeassistant: funziona , non ci sarei mai arrivato
