### ISSUE TITLE
Messaggio 

### ISSUE THREAD

**Issue by riddik14** [mariocandida80/cronotermostato#7]
Nelle automazioni di invio messaggio state.sensor.temperatura_attuale.state dove lo imposto? Devi creare io un sensore con quel nome o possiamo inserirlo in alto nelle impostazioni del package?
Mi arriva un messaggio vuoto.
![4CB79200-8FF2-4A7E-AB5B-249B978A4692](https://user-images.githubusercontent.com/37450907/78771553-a04eed00-7990-11ea-9577-2082d1296b1b.jpeg)

![image](https://user-images.githubusercontent.com/37450907/78771701-e5731f00-7990-11ea-84b7-b83b88abf9fd.jpg)

**Comment by mariocandida80** [comment]
Nella parte setup va inserito anche il sensore della temperatura. Mi sembra strano che non risulti ne la temperatura attuale e ne quella impostata. Prova a riavviare e vedi se va

**Comment by riddik14** [comment]
infatti manca nel file no climate sotto setting

    ##--------------------- IMPOSTAZIONI DEL PACKAGE ---------------------##

       setting:
        Sensore Temperatura: &sens_temp 'sensor.ir_clima'      #sostituire con il sensore della temperatura
    ##---------------------                           ---------------------##

**Comment by mariocandida80** [comment]
Nel no climate la temperatura la prende direttamente dal tuo climate. Il sensore temperatura attuale risulta vuoto? Ti da come valore unknown? Voglio capire se il problema sta nella lettura del sensore o nella formattazione del messaggio

**Comment by mariocandida80** [comment]
Sto effettuando delle prove e purtroppo il problema è che l'anchor *termostato dentro un template non lo vede. Sto cercando una soluzione

**Comment by mariocandida80** [comment]
Penso che la soluzione migliore sia ricopiare il proprio climate nel package, usando l'altro, il package standard intendo. Probabilmente cancellerò la versione no climate e riscriverò parte delle guida per adattarla a chi ha già installato un termostato su home assistant. Nel frattempo faccio altre prove.

**Comment by mariocandida80** [comment]
All'inizio alla versione no_climate bisognava apportare delle modifiche manualmente nel package, oltre alla parte setup. Ho cercato di evitare tali modifiche ma, purtroppo, vanno fatte lo stesso. Per ora riscarica il package ed effettua le seguenti modifiche, sostituendo *termostato con la tua entità climate (climate.termostato ad esempio).
Riga 160 e riga 167.
Riavvia e vedrai che dovrebbe funzionare

**Comment by mariocandida80** [comment]
Per ora ho optato per modificare la guida. Mi dispiace far modificare anche altre parti ma è l'unica soluzione. Se dovessi riuscire ad apportare una modifica che mi richiama un attributo di un anchor,  lo scriverò anche qui. Lascerò aperto questo issue.

**Comment by riddik14** [comment]
Allora io ho preso la stringa che invia il messaggio è messo climate.riscaldamento al posto della funzione che prende i dati dal setting e provata in strumenti sviluppatori e funziona. Stessa cosa per la temperatura è funziona, quindi può essere la funzione che prende il dato da settings?

**Comment by mariocandida80** [comment]
Si, il problema è quello. Nei template, tipo: "{{ state_attr('*termostato', 'current_temperature') }}", home assistant quando va alla ricerca dell'attributo current_temperature va in errore perché vorrebbe l'entità *termostato che non esiste ma è un anchor. Purtroppo gli anchor non possono andare nei template. Io consiglio di usare l'altro package inserendo il tuo climate al posto di quello presente. Conserva una copia da parte della configurazione del tuo climate (e magari anche della parte setup) così potrai fare subito quando ci saranno degli aggiornamenti.

**Comment by riddik14** [comment]
si la temperatura ora esce nel messaggio
