### ISSUE TITLE
Temperatura Termostato

### ISSUE THREAD

**Issue by ocram76** [mariocandida80/cronotermostato#8]
Ciao scusa il disturbo, sono riuscito a configurare tutto ed ora sembra funzionare.
Unica cosa che noto è che la temperatura del termostato mi riferisco a quella da impostare che la freccia su e freccia giu, varia in continuazione senza toccarla e non mi permette di alzarla ed abbassarla. Inoltre in modalità automatico, nonostante il traker mi localizza il termostato non parte.
Ti è capitato puoi darmi per cortesia delle dritte?
Grazie.

**Comment by mariocandida80** [comment]
Mai capitato nessuna delle 2 cose. Prova a ricaricare le automazioni o riavviare home assistant. Per quanto riguarda la modalità auto che non parte, fai le seguenti verifiche: 
in manuale funziona?
controlla la parte setup se hai settato bene il tuo tracker
controlla che la zona sia 'home'
la fascia oraria sia impostata per un orario di accensione

**Comment by ocram76** [comment]
si in manuale funziona

**Comment by mariocandida80** [comment]
Fai anche gli altri controlli. Prova ad azionarlo in modalità PRE. Se si accende il problema è il tracker, se non si accende, il problema è la fascia oraria.

**Comment by ocram76** [comment]
ok provo

**Comment by mariocandida80** [comment]
Funziona?

**Comment by ocram76** [comment]
Si, funzione in PRE ma non in auto, provo a rivedere la configurazione del tracker.
Se posso tu che tracker usi?

**Comment by mariocandida80** [comment]
Io uso un'iphone con l'integrazione apposita. Mi posti la tua parte setup? Fai anche una verifica, vai in strumenti sviluppatori, stati e metti il tracker che hai messo nel setup e vedi che stato ti risulta. Dovrebbe essere home.

**Comment by ocram76** [comment]
Cioè Home Assistant companion? Lo stato risulta not_home.

setting:
        Interruttore Caldaia: &caldaia 'switch.unita_termica'           #sostituire con l'interruttore che attiva la caldaia
        Sensore Temperatura: &sens_temp 'sensor.temperatura_ambiente'      #sostituire con il sensore della temperatura
        Tracker: &tracker 'device_tracker.sm_g973f'
        Zona_casa: &zona 'Home'
        Servizio Notifica: &servizio 'notify.marco'

**Comment by mariocandida80** [comment]
Il problema di sicuro è il tracker allora che non si aggiorna, non risulti a casa.
Cosa usi tu come tracker? Se usi il telefono, controlla di aver dato le autorizzazioni per la localizzazione e controlla che sia abilitata la localizzazione. Poi controlla anche la configurazione in home assistant, probabilmente c'è qualcosa che non va.
Nel setup home deve essere scritto tutto in minuscolo così Zona_casa: &zona 'home'

**Comment by ocram76** [comment]
Home Assistant companion sul telefono con gps abilitato e autorizzazione. controllo il configuration

**Comment by mariocandida80** [comment]
Beh se non riesci a configurare bene il tracker, non ti funzionerà mai in modalità auto purtroppo. Aggiornami

**Comment by ocram76** [comment]
ok ti aggiorno. grazie della pazienza

**Comment by mariocandida80** [comment]
tranquillo, sono qui per aiutare

**Comment by mariocandida80** [comment]
> ok ti aggiorno. grazie della pazienza

Sei riuscito poi a configurare il tracker? Se vuoi posso aiutarti

**Comment by ocram76** [comment]
Ciao. Utilizzando  il tracker del router e quindi il wifi tutto funziona. Ho fatto mille prove con il tracker dell'appartamento di home assistant per android ma nulla non va. Tu in questo mi puoi aiutare?

**Comment by mariocandida80** [comment]
Che tracker usi?

**Comment by ocram76** [comment]
App di home assistant lo crea in automatico

**Comment by mariocandida80** [comment]
Ma se vai in strumenti per sviluppatori, che stato risulta?

**Comment by ocram76** [comment]
Not home. Se manualmente imposto home, allora funziona. Quindi penso ci sia un bug nell'app per android. Bo non saprei. Comunque con un tracker diverso funziona tutto bene.

**Comment by mariocandida80** [comment]
Ti consiglio di disinstallare e reinstallare l’app. Con iPhone una volta mi è successo.

**Comment by ocram76** [comment]
Purtroppo ho fatto questa operazione diverse volte sia sul tablet che smartphone con sistemi operativi diversi, seguendo la guida ufficiale, ma il problema resta, pensa non mi riconosce nemmeno la rete locale dove si trova hassio

**Comment by mariocandida80** [comment]
Beh comunque è strano. Ma hai settato bene latitudine e longitudine?

**Comment by ocram76** [comment]
Si settanta, ma che tu sai, nel file configurazione.yaml, va inserito codice di configurazione? Tu lo hai fatto? Intendo con l'utilizzo del app di HA

**Comment by mariocandida80** [comment]
Vado a memoria, in configuration basta solo discovery: e poi esce nelle integrazioni, questo almeno per iPhone.

**Comment by ocram76** [comment]
Ok grazie della tua disponibilità e del supporto. Ciao
