### ISSUE TITLE
Avere piu termostati

### ISSUE THREAD

**Issue by andreaconfa** [mariocandida80/cronotermostato#9]
Ciao, funziona alla perfezione ma come devo comportarmi se voglio integrarne due.. per gestire due zone?

**Comment by mariocandida80** [comment]
Questo package è stato concepito per funzionare con 1 solo termostato. Per farlo funzionare con un secondo termostato, bisognerebbe rinominare un po' ' di entità ed automazioni. Nelle prossime settimane pubblicherò un package aggiuntivo per un secondo termostato. Mi è stato chiesto da più persone. Purtroppo ora non riesco a dedicare tempo. Lascio aperto questo issue così scriverò qui quando lo pubblicherò.

**Comment by andreaconfa** [comment]
il package che pubblicherai per il secondo termostato sarà in versione settimanale?
come pensi di fare la cosa? crei un altro package per il secondo termostato? se cosi fosse poi per me dovrebbe essere facile trovare le differenze trai due per capire che entità rinominare e crearmi cosi un terzo package....

**Comment by mariocandida80** [comment]
Creerò un secondo package identico a quello che già c'è ma con nomi diversi. Oltre al package del termostato, farò anche l'addon settimanale e la card lovelace.

**Comment by michelecarandente** [comment]
grazie mario per lo spendido lavoro. Mi sto avvicinando ora ad homeassistant ed ho già climate e sto provando a mettere il tuo software per il termostato. Ho una domanda davvero stupida, ma sto bloccato e spero in una indicazione: dici di copiare i files in questo modo:
Pkg_cronotermostato.yaml nella cartella packages
blu.jpg, impostazioni.jpg e fiamma.gif nella cartella www/immagini/lovelace/

ma nella mia installazione, su raspberry, ho i files.yaml nella cartella /config e non ho la cartella packages (ho li la cartella custom_components dove ho ad esempio le cartelle hacs, smartir etc). Sbaglio qualcosa? Grazie

**Comment by mariocandida80** [comment]
Grazie per i complimenti. Leggi bene la guida, c’è scritto tutto. Se clicchi su package nella sezione prerequisiti, ho creato una piccola guida su come si installano i package

**Comment by mariocandida80** [comment]
@andreaconfa ho aggiunto un altro package modificando i nomi delle entità. Non l’ho potuto testare ma dovrebbe funzionare. Se ci dovessero essere dei bug, apri un issue sull’altra repo. https://github.com/mariocandida80/secondo_cronotermostato
